name: Linux Script

on:
  push:
    branches:
      - main

jobs:
  linux-script:
    runs-on: ubuntu-latest

    steps:
      - name: Linux commands
        run: |
          pwd
          ls -la
          whoami
          uname -a
